/**
 * Chart color-theme stops for the Components → Data Visualization panel.
 *
 * Source of truth: `chart-tool-echarts/src/tokens/tokens.json` → `paletteTokens`
 * (generated by `chart-tool-echarts` `npm run build:tokens` from hero tones).
 * Wireframe shades are the light-mode secondary ramp from
 * `buildColorSystem` / `colorScales.ts` (variation `secondary`, 6 stops before
 * patterns) — same preview ColorControls uses.
 *
 * Fixed palettes (categorical / sequential / semantic / diverging) are identical
 * in light and dark; wireframe greys are the light-mode secondary derivation.
 */

export const DATAVIZ_THEME_SWATCHES = {
  Categorical: [
    { name: 'hero.indigo.60', color: '#7586ff' },
    { name: 'hero.cyan.70', color: '#00bbdf' },
    { name: 'hero.yellow.80', color: '#e2c600' },
    { name: 'hero.pink.60', color: '#f65396' },
    { name: 'hero.jade.70', color: '#2cc27e' },
    { name: 'hero.amber.70', color: '#fb911c' },
    { name: 'hero.lime.70', color: '#9db600' },
    { name: 'hero.purple.70', color: '#dd8aff' },
    { name: 'hero.gold.80', color: '#fcbb42' },
    { name: 'hero.blue.70', color: '#75adfd' },
    { name: 'hero.red.70', color: '#ff8886' },
    { name: 'hero.pure neutral.70', color: '#ababab' },
  ],
  Sequential: [
    { name: 'hero.indigo.80', color: '#bcc3ff' },
    { name: 'hero.indigo.70', color: '#98a4ff' },
    { name: 'hero.indigo.60', color: '#7586ff' },
    { name: 'hero.indigo.50', color: '#5066ff' },
    { name: 'hero.indigo.40', color: '#394edb' },
    { name: 'hero.indigo.30', color: '#2034b7' },
  ],
  Semantic: [
    { name: 'hero.red.50', color: '#df2e3c' },
    { name: 'hero.amber.80', color: '#ffb779' },
    { name: 'hero.yellow.90', color: '#f9e374' },
    { name: 'hero.lime.80', color: '#b9d237' },
    { name: 'hero.green.60', color: '#4aa42c' },
  ],
  Diverging: [
    { name: 'hero.jade.70', color: '#2cc27e' },
    { name: 'hero.jade.80', color: '#44df95' },
    { name: 'hero.warm  neutral.95', color: '#f3f0e7' },
    { name: 'hero.violet.70', color: '#b89bff' },
    { name: 'hero.violet.40', color: '#6d35e0' },
  ],
  Wireframe: [
    { name: 'wireframe.shade.1', color: '#393737' },
    { name: 'wireframe.shade.2', color: '#e6e4e4' },
    { name: 'wireframe.shade.3', color: '#585656' },
    { name: 'wireframe.shade.4', color: '#c1bebe' },
    { name: 'wireframe.shade.5', color: '#7a7777' },
    { name: 'wireframe.shade.6', color: '#9c9a9a' },
  ],
};
