/** Auto-generated — run `node scripts/gen-region-names.mjs`. */
export const CONTINENT_NAMES = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania"
] as const;
export type ContinentName = (typeof CONTINENT_NAMES)[number];

export const COUNTRY_NAMES: string[] = [
  "",
  "",
  "Afghanistan",
  "Aland",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Antigua and Barb.",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herz.",
  "Botswana",
  "Br. Indian Ocean Ter.",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Is.",
  "Central African Rep.",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Rep.",
  "Dem. Rep. Congo",
  "Dem. Rep. Korea",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Rep.",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Eq. Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Faeroe Is.",
  "Falkland Is.",
  "Fiji",
  "Finland",
  "Fr. Polynesia",
  "Fr. S. Antarctic Lands",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard I. and McDonald Is.",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao PDR",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "N. Cyprus",
  "N. Mariana Is.",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "S. Geo. and S. Sandw. Is.",
  "S. Sudan",
  "Saint Helena",
  "Saint Lucia",
  "Samoa",
  "São Tomé and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Siachen Glacier",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Is.",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "St. Pierre and Miquelon",
  "St. Vin. and Gren.",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Is.",
  "U.S. Virgin Is.",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "W. Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

/** Country GeoJSON name → continent (for dissolving country polygons). */
export const CONTINENT_BY_COUNTRY: Record<string, string> = {
  "Algeria": "Africa",
  "Angola": "Africa",
  "Benin": "Africa",
  "Botswana": "Africa",
  "Burkina Faso": "Africa",
  "Burundi": "Africa",
  "Cameroon": "Africa",
  "Cape Verde": "Africa",
  "Central African Rep.": "Africa",
  "Chad": "Africa",
  "Comoros": "Africa",
  "Congo": "Africa",
  "Côte d'Ivoire": "Africa",
  "Dem. Rep. Congo": "Africa",
  "Djibouti": "Africa",
  "Egypt": "Africa",
  "Eq. Guinea": "Africa",
  "Eritrea": "Africa",
  "Ethiopia": "Africa",
  "Gabon": "Africa",
  "Gambia": "Africa",
  "Ghana": "Africa",
  "Guinea": "Africa",
  "Guinea-Bissau": "Africa",
  "Kenya": "Africa",
  "Lesotho": "Africa",
  "Liberia": "Africa",
  "Libya": "Africa",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Mali": "Africa",
  "Mauritania": "Africa",
  "Mauritius": "Africa",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Namibia": "Africa",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "Rwanda": "Africa",
  "S. Sudan": "Africa",
  "Saint Helena": "Africa",
  "São Tomé and Principe": "Africa",
  "Senegal": "Africa",
  "Seychelles": "Africa",
  "Sierra Leone": "Africa",
  "Somalia": "Africa",
  "South Africa": "Africa",
  "Sudan": "Africa",
  "Swaziland": "Africa",
  "Tanzania": "Africa",
  "Togo": "Africa",
  "Tunisia": "Africa",
  "Uganda": "Africa",
  "W. Sahara": "Africa",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",
  "Afghanistan": "Asia",
  "Armenia": "Asia",
  "Azerbaijan": "Asia",
  "Bahrain": "Asia",
  "Bangladesh": "Asia",
  "Bhutan": "Asia",
  "Brunei": "Asia",
  "Cambodia": "Asia",
  "China": "Asia",
  "Cyprus": "Asia",
  "N. Cyprus": "Asia",
  "Dem. Rep. Korea": "Asia",
  "Georgia": "Asia",
  "India": "Asia",
  "Indonesia": "Asia",
  "Iran": "Asia",
  "Iraq": "Asia",
  "Israel": "Asia",
  "Japan": "Asia",
  "Jordan": "Asia",
  "Kazakhstan": "Asia",
  "Korea": "Asia",
  "Kuwait": "Asia",
  "Kyrgyzstan": "Asia",
  "Lao PDR": "Asia",
  "Lebanon": "Asia",
  "Malaysia": "Asia",
  "Mongolia": "Asia",
  "Myanmar": "Asia",
  "Nepal": "Asia",
  "Oman": "Asia",
  "Pakistan": "Asia",
  "Palestine": "Asia",
  "Philippines": "Asia",
  "Qatar": "Asia",
  "Russia": "Asia",
  "Saudi Arabia": "Asia",
  "Singapore": "Asia",
  "Sri Lanka": "Asia",
  "Syria": "Asia",
  "Tajikistan": "Asia",
  "Thailand": "Asia",
  "Timor-Leste": "Asia",
  "Turkey": "Asia",
  "Turkmenistan": "Asia",
  "United Arab Emirates": "Asia",
  "Uzbekistan": "Asia",
  "Vietnam": "Asia",
  "Yemen": "Asia",
  "Siachen Glacier": "Asia",
  "Br. Indian Ocean Ter.": "Asia",
  "Aland": "Europe",
  "Albania": "Europe",
  "Andorra": "Europe",
  "Austria": "Europe",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Bosnia and Herz.": "Europe",
  "Bulgaria": "Europe",
  "Croatia": "Europe",
  "Czech Rep.": "Europe",
  "Denmark": "Europe",
  "Estonia": "Europe",
  "Faeroe Is.": "Europe",
  "Finland": "Europe",
  "France": "Europe",
  "Germany": "Europe",
  "Greece": "Europe",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "Ireland": "Europe",
  "Isle of Man": "Europe",
  "Italy": "Europe",
  "Jersey": "Europe",
  "Latvia": "Europe",
  "Liechtenstein": "Europe",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  "Macedonia": "Europe",
  "Malta": "Europe",
  "Moldova": "Europe",
  "Montenegro": "Europe",
  "Netherlands": "Europe",
  "Norway": "Europe",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Romania": "Europe",
  "Serbia": "Europe",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Spain": "Europe",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Ukraine": "Europe",
  "United Kingdom": "Europe",
  "Antigua and Barb.": "North America",
  "Bahamas": "North America",
  "Barbados": "North America",
  "Belize": "North America",
  "Bermuda": "North America",
  "Canada": "North America",
  "Cayman Is.": "North America",
  "Costa Rica": "North America",
  "Cuba": "North America",
  "Curaçao": "North America",
  "Dominica": "North America",
  "Dominican Rep.": "North America",
  "El Salvador": "North America",
  "Greenland": "North America",
  "Grenada": "North America",
  "Guatemala": "North America",
  "Haiti": "North America",
  "Honduras": "North America",
  "Jamaica": "North America",
  "Mexico": "North America",
  "Montserrat": "North America",
  "Nicaragua": "North America",
  "Panama": "North America",
  "Puerto Rico": "North America",
  "Saint Lucia": "North America",
  "St. Pierre and Miquelon": "North America",
  "St. Vin. and Gren.": "North America",
  "Trinidad and Tobago": "North America",
  "Turks and Caicos Is.": "North America",
  "U.S. Virgin Is.": "North America",
  "United States": "North America",
  "Argentina": "South America",
  "Bolivia": "South America",
  "Brazil": "South America",
  "Chile": "South America",
  "Colombia": "South America",
  "Ecuador": "South America",
  "Falkland Is.": "South America",
  "Guyana": "South America",
  "Paraguay": "South America",
  "Peru": "South America",
  "Suriname": "South America",
  "Uruguay": "South America",
  "Venezuela": "South America",
  "S. Geo. and S. Sandw. Is.": "South America",
  "American Samoa": "Oceania",
  "Australia": "Oceania",
  "Fiji": "Oceania",
  "Fr. Polynesia": "Oceania",
  "Guam": "Oceania",
  "Kiribati": "Oceania",
  "Micronesia": "Oceania",
  "N. Mariana Is.": "Oceania",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  "Niue": "Oceania",
  "Palau": "Oceania",
  "Papua New Guinea": "Oceania",
  "Samoa": "Oceania",
  "Solomon Is.": "Oceania",
  "Tonga": "Oceania",
  "Vanuatu": "Oceania",
  "Heard I. and McDonald Is.": "Oceania",
  "Fr. S. Antarctic Lands": "Oceania",
  "": "Asia"
};

export function regionNamesFor(grain: 'country' | 'continent'): readonly string[] {
  if (grain === 'continent') return CONTINENT_NAMES;
  // GeoJSON can include blank feature names — never offer those in the picker.
  return COUNTRY_NAMES.filter((n) => n.trim().length > 0);
}
